plugins {
    id 'java'
    id 'org.springframework.boot' version '2.3.4.RELEASE'
    id 'io.spring.dependency-management' version '1.0.8.RELEASE'
}

group 'com.deva.kafka.admin'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation('org.springframework.boot:spring-boot-starter-web')
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation('org.apache.kafka:kafka_2.12')
    implementation('org.apache.kafka:kafka-clients')
}

bootJar {
    mainClassName = 'com.deva.kafka.admin.application.KafkaAdminWebApplication'
}