plugins {
    id 'java'
    id 'org.springframework.boot' version '2.3.4.RELEASE'
    id 'io.spring.dependency-management' version '1.0.8.RELEASE'
    id 'war'
    //id "com.moowork.node" version "1.3.1"
    id "com.github.node-gradle.gulp" version "1.3.0"
}
apply plugin: 'com.github.node-gradle.gulp'

war {
    baseName = 'spring-boot-jsp-sample'
    version = '0.0.1-SNAPSHOT'
}

sourceCompatibility = 1.8
targetCompatibility = 1.8

repositories {
    mavenCentral()
}

node {
	version = '12.14.1'
	download = true
	workDir = file("${project.projectDir}/node_base/nodejs")
	npmWorkDir = file("${project.projectDir}/node_base/npm")
	nodeModulesDir = file("${project.projectDir}/node_base") 
}

task npmInstallDependencies(type:NpmTask){
	dependsOn 'npmSetup'
	execOverrides {
		it.ignoreExitValue = true
		it.workingDir = 'node_base'
	}
	args = ['install']
}

task npmBuild(type:NpmTask){
	dependsOn 'npmInstallDependencies'
	execOverrides {
		it.workingDir = 'node_base'
	}
	args = ['run','build']
}

task copyNodeBaseToBuild(type:Copy){
	dependsOn 'npmBuild'
	from "${project.projectDir}/node_base/build"
	into "${project.projectDir}/src/main/webapp"
}

processResources{
	dependsOn 'copyNodeBaseToBuild'
}

configurations {
    providedRuntime
}

dependencies {
	compile('org.springframework.boot:spring-boot-devtools')
    implementation('org.springframework.boot:spring-boot-starter-web')
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation('org.apache.kafka:kafka_2.12')
    implementation('org.apache.kafka:kafka-clients')
    compile('javax.servlet:jstl')
    providedRuntime('org.springframework.boot:spring-boot-starter-tomcat')
    providedRuntime('org.apache.tomcat.embed:tomcat-embed-jasper')
}

bootJar {
    mainClassName = 'com.deva.kafka.admin.application.KafkaAdminWebApplication'
}

